# Example secrets configuration for Tiangong LCA spec coding workflow.
# Copy to .secrets/secrets.toml and replace placeholder values with real credentials.

[OPENAI]
API_KEY = "<YOUR_OPENAI_API_KEY>"
MODEL = "gpt-5"

[tiangong_lca_remote]
transport = "streamable_http"
service_name = "tiangong_lca_remote"
url = "https://lcamcp.tiangong.earth/mcp"
api_key = "<YOUR_TG_LCA_REMOTE_API_KEY>"
timeout = 180  # seconds
